name: FutureFlex Surfboards
favicon: null
layout_spectrum: 0.4606368199456483
typography_spectrum: 0.44498667283914983
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.05856316792778671
  lightness: 0.7423875187523663
  saturation: 0.2332316858228296
  rhythmicContrast: 0.3517918959259987
purpose: []
